In [1]:
import numpy as np

# Data Types

In [5]:
x = np.float32(1.0)
x

1.0

In [6]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [7]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [8]:
np.array([1,2,3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [9]:
z.astype(float)

array([0., 1., 2.])

In [10]:
np.int8(z)

array([0, 1, 2], dtype=int8)

In [11]:
z.dtype

dtype('uint8')

In [12]:
d = np.dtype(int)
d

dtype('int64')

In [13]:
np.issubdtype(d, np.integer)

True

In [14]:
np.issubdtype(d, np.floating)

False

In [15]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [16]:
np.power(100, 8, dtype=np.int32)

1874919424

In [17]:
np.iinfo(np.int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [18]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [19]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [20]:
np.power(100, 100, dtype=np.int64)

0

In [21]:
np.power(100, 100, dtype=np.float64)

1e+200

In [22]:
np.finfo(np.longdouble)

finfo(resolution=1.0000000000000000715e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [23]:
np.finfo(np.clongdouble)

finfo(resolution=1.0000000000000000715e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [24]:
np.finfo(np.longdouble).eps

1.084202172485504434e-19

In [25]:
1 + np.finfo(np.longdouble).eps

1.0000000000000000001

# Array Creation

In [26]:
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [31]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [32]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

# IO

In [33]:
import numpy as np
from io import StringIO

In [34]:
data = u"1, 2, 3\n4, 5, 6"

In [35]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
data = u"  1  2  3\n  4  5 67\n890123  4"

In [37]:
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [38]:
data = u"123456789\n   4  7 9\n   4567 9"

In [39]:
np.genfromtxt(StringIO(data), delimiter=(4,3,2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [40]:
data = u"1, abc , 2\n 3, xxx, 4"

In [41]:
np.genfromtxt(StringIO(data), delimiter=',', dtype='|U5')

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [42]:
np.genfromtxt(StringIO(data), delimiter=',', dtype='|U5', autostrip=True)

array([['1', 'abc', '2'],
       ['3', 'xxx', '4']], dtype='<U5')

In [43]:
data = u"""#
 # Skip me !
 # Skip me too !
 1, 2
 3, 4
 5, 6 #This is the third line of the data
 7, 8
 # And here comes the last line
 9, 0
 """

In [45]:
np.genfromtxt(StringIO(data), comments='#', delimiter=',')

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [48]:
data = u'\n'.join(str(i) for i in range(10))

In [49]:
np.genfromtxt(StringIO(data))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
np.genfromtxt(StringIO(data), skip_header=3, skip_footer=5)

array([3., 4.])

In [69]:
data = u"1 2 3\n4 5 6"

In [53]:
np.genfromtxt(StringIO(data), usecols=(0, -1))

array([[1., 3.],
       [4., 6.]])

In [54]:
np.genfromtxt(StringIO(data), names='a, b, c', usecols=('a', 'c'))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [55]:
np.genfromtxt(StringIO(data), dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
np.genfromtxt(StringIO(data), dtype=(int, float, float))

array([(1, 2., 3.), (4, 5., 6.)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<f8')])

In [57]:
np.genfromtxt(StringIO(data), dtype='i4, f8, |U3')

array([(1, 2., '3'), (4, 5., '6')],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<U3')])

In [60]:
np.genfromtxt(StringIO(data), dtype={'names':['a', 'b', 'c'], 'formats': ['i4', 'f8', '|U3']})

array([(1, 2., '3'), (4, 5., '6')],
      dtype=[('a', '<i4'), ('b', '<f8'), ('c', '<U3')])

In [61]:
np.genfromtxt(StringIO(data), dtype=[('a', int), ('b', float), ('c', '|U3')])

array([(1, 2., '3'), (4, 5., '6')],
      dtype=[('a', '<i8'), ('b', '<f8'), ('c', '<U3')])

In [62]:
np.genfromtxt(StringIO(data), dtype=None)

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.genfromtxt(StringIO(data), dtype=[(_, int) for _ in 'abc'])

array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [71]:
np.genfromtxt(StringIO(data), names='A, B, C')

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [72]:
data = 'So it goes\n#a b c\n1 2 3\n4 5 6'
np.genfromtxt(StringIO(data), skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [73]:
data = StringIO('1 2 3\n4 5 6')
ndtype = [('a', int), ('b', float), ('c', int)]
names = ['A', 'B', 'C']
np.genfromtxt(data, names=names, dtype=ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('A', '<i8'), ('B', '<f8'), ('C', '<i8')])

In [74]:
data = StringIO('1 2 3\n4 5 6')
np.genfromtxt(data, dtype=(int,float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In [75]:
data = StringIO('1 2 3\n4 5 6')
np.genfromtxt(data, dtype=(int, float, int), names='a')

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('a', '<i8'), ('f0', '<f8'), ('f1', '<i8')])

In [76]:
data = StringIO('1 2 3\n4 5 6')
np.genfromtxt(data, dtype=(int, float, int), defaultfmt='var_%02i')

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_00', '<i8'), ('var_01', '<f8'), ('var_02', '<i8')])

In [138]:
del x

In [145]:
convertfunc = lambda x: float(x.decode('utf-8').strip(" %"))/100.
data = "1, 2.3%, 45.\n6, 78.9%, 0"
names = ("i", "p", "n")
# General case .....
np.genfromtxt(StringIO(data), delimiter=",", names=names)

array([(1., nan, 45.), (6., nan,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [146]:
np.genfromtxt(StringIO(data), delimiter=",", names=names, converters={1: convertfunc})

array([(1., 0.023, 45.), (6., 0.789,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [147]:
np.genfromtxt(StringIO(data), delimiter=",", names=names, converters={"p": convertfunc})

array([(1., 0.023, 45.), (6., 0.789,  0.)],
      dtype=[('i', '<f8'), ('p', '<f8'), ('n', '<f8')])

In [158]:
data = u"1, , 3\n 4, 5, 6"
convert = lambda x: float(x.decode('utf-8').strip() or -999)
np.genfromtxt(StringIO(data), delimiter=",", converters={1: convert})

array([[   1., -999.,    3.],
       [   4.,    5.,    6.]])

In [159]:
data = u'N/A, 2, 3\n4, ,???'

In [160]:
kwargs = dict(delimiter=',',
              dtype=int,
              names='a,b,c',
              missing_values={0: 'N/A', 'b': ' ', 2:'???'},
              filling_values={0:0, 'b':0, 2:-999})

In [161]:
np.genfromtxt(StringIO(data), **kwargs)

array([(0, 2,    3), (4, 0, -999)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

# Indexing

In [164]:
x = np.arange(10)

In [165]:
x[2]

2

In [166]:
x[-2]

8

In [168]:
x.shape = (2,5)

In [169]:
x[1,3]

8

In [170]:
x[1,-1]

9

In [171]:
x[0]

array([0, 1, 2, 3, 4])

In [187]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
x[2:5]

array([2, 3, 4])

In [175]:
x[:-7]

array([0, 1, 2])

In [176]:
x[1:7:2]

array([1, 3, 5])

In [186]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [178]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [179]:
x = np.arange(10,1,-1)

In [180]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [181]:
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [183]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [184]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

In [185]:
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [189]:
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [190]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [191]:
b = y > 20
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [198]:
b[:,0]

array([False, False, False,  True,  True])

In [196]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [197]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [200]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [201]:
b = np.array([[True, True, False], [False, True, True]])

In [202]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [204]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [205]:
b = y > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [207]:
y[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

In [208]:
y.shape

(5, 7)

In [209]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [212]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [213]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [214]:
x[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [211]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [215]:
z = np.arange(81).reshape(3,3,3,3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [216]:
z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [217]:
z[1]

array([[[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [218]:
z[...,2]

array([[[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]],

       [[29, 32, 35],
        [38, 41, 44],
        [47, 50, 53]],

       [[56, 59, 62],
        [65, 68, 71],
        [74, 77, 80]]])

In [221]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [223]:
x[2:7] = np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [226]:
x[1] = 1.2
x[1]

1

In [230]:
x = np.arange(0, 50, 10)
x 

array([ 0, 10, 20, 30, 40])

In [231]:
x[np.array([1,1,3,1])] += 1
x

array([ 0, 11, 20, 31, 40])

In [232]:
indices = (1,1,1,1)
z[indices]

40

In [234]:
indices = (1,1,1,slice(0,2))
z[indices]

array([39, 40])

In [235]:
indices = (1, Ellipsis, 1)
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [236]:
z[[1,1,1,1]]

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [237]:
z[(1,1,1,1)]

40

# Broadcasting

In [240]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [242]:
b = np.array([2., 2., 2.])
b

array([2., 2., 2.])

In [243]:
a * b

array([2., 4., 6.])

In [244]:
a * 2.

array([2., 4., 6.])

In [245]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [247]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [248]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [250]:
z = np.ones((3,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [251]:
x.shape

(4,)

In [252]:
y.shape

(5,)

In [254]:
xx.shape

(4, 1)

In [255]:
xx + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [256]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [257]:
a = np.array([0., 10., 20., 30.])
a

array([ 0., 10., 20., 30.])

In [259]:
b = np.array([1., 2., 3.])
b

array([1., 2., 3.])

In [261]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [262]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# Byte-swapping

In [263]:
big_end_buffer = bytearray([0,1,3,2])
big_end_buffer

bytearray(b'\x00\x01\x03\x02')

In [264]:
big_end_arr = np.ndarray(shape=(2,), dtype='>i2', buffer=big_end_buffer)
big_end_arr

array([  1, 770], dtype=int16)

In [265]:
big_end_arr.dtype

dtype('>i2')

In [267]:
little_end_u4 = np.ndarray(shape=(1,), dtype='<u4', buffer=big_end_buffer)
little_end_u4

array([33751296], dtype=uint32)

In [268]:
little_end_u4.dtype

dtype('uint32')

In [269]:
little_end_u4[0] == 1 * 256**1 + 3 * 256**2 + 2 * 256**3

True

In [270]:
big_end_arr[0].dtype.byteorder == little_end_u4[0].dtype.byteorder

True

In [272]:
wrong_end_dtype_arr = np.ndarray(shape=(2,),dtype='<i2', buffer=big_end_buffer)
wrong_end_dtype_arr

array([256, 515], dtype=int16)

In [273]:
fixed_end_dtype_arr = wrong_end_dtype_arr.newbyteorder()
fixed_end_dtype_arr

array([  1, 770], dtype=int16)

In [274]:
fixed_end_dtype_arr.tobytes() == big_end_buffer

True

In [275]:
fixed_end_mem_arr = wrong_end_dtype_arr.byteswap()
fixed_end_mem_arr

array([  1, 770], dtype=int16)

In [276]:
fixed_end_mem_arr.tobytes() == big_end_buffer

False

In [277]:
swapped_end_arr = big_end_arr.astype('<i2')
swapped_end_arr

array([  1, 770], dtype=int16)

In [278]:
swapped_end_arr.tobytes() == big_end_buffer

False